<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHbEJSqI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHbEJSqI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHbEJSqI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHbEJSqI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHbEJSqI\App_KernelDevDebugContainer([
    'container.build_hash' => 'HbEJSqI',
    'container.build_id' => 'b2c5c5db',
    'container.build_time' => 1646730879,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHbEJSqI');
